-   id: rolint
    name: RoLint
    description: Lint C/C++/Python code for robotics safety
    entry: rolint check
    language: python
    types: [c, c++, python]
    require_serial: false
    pass_filenames: true
    args: [--output, text]
    additional_dependencies: ['./RoLint']

-   id: rolint-json
    name: RoLint (JSON output)
    description: Lint C/C++/Python code for robotics safety with JSON output
    entry: rolint check
    language: python
    types: [c, c++, python]
    require_serial: false
    pass_filenames: true
    args: [--output, json, --output-path, rolint_results.json]
    additional_dependencies: ['./RoLint']